apiVersion: v1
kind: Pod
metadata:
  name: test-log-pod-logging
  namespace: logging
  annotations:
    eks.amazonaws.com/logging: enabled
    eks.amazonaws.com/log-group: /aws/eks/protein-engineering-cluster-new/logging
spec:
  containers:
  - name: log-generator
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "ERROR: This is an error message that should be captured from logging namespace"
          echo "FATAL ERROR: Critical system failure simulation from logging namespace"
          echo "INFO: This message should be filtered out"
          sleep 5
        done
