apiVersion: v1
kind: Pod
metadata:
  name: test-log-pod
  namespace: test-app
  annotations:
    eks.amazonaws.com/logging: enabled
spec:
  containers:
  - name: log-generator
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "FATAL: System failure simulation"
          echo "ERROR: This is a test error message"
          sleep 5
        done
