apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: test-app
  labels:
    k8s-app: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
        imagePullPolicy: Always
        env:
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_ROLE_ARN
            valueFrom:
              configMapKeyRef:
                name: aws-logging
                key: role-arn
          - name: FLB_LOG_LEVEL
            value: "trace"
          - name: AWS_SDK_LOG_LEVEL
            value: "LogDebug"
          - name: FLUENT_AWS_LOG_LEVEL
            value: "debug"
          - name: AWS_STS_REGIONAL_ENDPOINTS
            value: "regional"
          - name: AWS_EC2_METADATA_DISABLED
            value: "false"
        volumeMounts:
        - name: fluentbitconfig
          mountPath: /fluent-bit/etc/
      volumes:
      - name: fluentbitconfig
        configMap:
          name: fluent-bit-config
