apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: test-app
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File    parsers.conf
        Log_Level      trace
        Daemon         off
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_Port      2020

    # Input is managed by AWS Fargate

    [FILTER]
        Name                kubernetes
        Match               *
        Merge_Log          On
        K8S-Logging.Parser On
        Annotations        Off
        Labels            On
        Buffer_Size       0

    [FILTER]
        Name                grep
        Match               *
        Regex              kubernetes.namespace_name test-app

    [FILTER]
        Name                grep
        Match               *
        Regex              log error|Error|ERROR|exception|Exception|EXCEPTION|fail|Fail|FAIL
        Debug              On

    [OUTPUT]
        Name                cloudwatch
        Match               *
        region              us-east-1
        log_group_name      /aws/eks/protein-engineering-cluster-new/test-app
        log_stream_prefix   fargate-
        auto_create_group   true
        log_key            log
        debug              On
        retry_limit        5
        net.dns.resolver   legacy
        sts_endpoint       https://sts.us-east-1.amazonaws.com
        log_retention_days 7
        metric_namespace   FluentBitEKS
        metric_dimensions  ["ClusterName=protein-engineering-cluster-new", "Namespace=test-app"]
        role_arn          ${AWS_ROLE_ARN}
        external_id       fluent-bit-cloudwatch
        auto_retry_requests true
        workers           1

  parsers.conf: |
    [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%L
        Time_Keep           On
        Decode_Field        json log
